export const TOGGLE_THEME = 'TOGGLE_THEME'
export const TOGGLE_FAVORITES = 'TOGGLE_FAVORITES'
export const TOGGLE_HIDDEN = 'TOGGLE_HIDDEN'

export const TOGGLE_DISPLAY_FAVORITES = 'TOGGLE_DISPLAY_FAVORITES'
export const TOGGLE_DISPLAY_HIDDEN = 'TOGGLE_DISPLAY_HIDDEN'
